BEGIN;
DO $$ BEGIN
 IF current_user <> 'postgres' OR session_user <> 'postgres' THEN
  RAISE EXCEPTION 'ROLLOUT_OWNER_REQUIRED: executar como operador postgres, sem SET ROLE da aplicação.' USING ERRCODE='42501';
 END IF;
END $$;
SET LOCAL lock_timeout='10s';
SET LOCAL search_path=public,pg_temp;
LOCK TABLE public.quadro_pessoal_alocacao,public.quadro_pessoal_movimentos IN SHARE MODE;
LOCK TABLE primeline_quadro_rollout.controlo,primeline_quadro_rollout.validacoes IN SHARE MODE;
SELECT primeline_quadro_rollout.exigir_validacao();
CREATE TABLE primeline_backup.quadro_fase_b_controlo_20261001 AS TABLE primeline_quadro_rollout.controlo;
CREATE TABLE primeline_backup.quadro_fase_b_validacoes_20261001 AS TABLE primeline_quadro_rollout.validacoes;
CREATE TABLE primeline_backup.quadro_fase_b_alocacoes_20261001 AS TABLE public.quadro_pessoal_alocacao;
CREATE TABLE primeline_backup.quadro_fase_b_movimentos_20261001 AS TABLE public.quadro_pessoal_movimentos;
CREATE TABLE primeline_backup.quadro_fase_b_revisoes_20261001 AS TABLE public.quadro_dias_revisoes;
CREATE TABLE primeline_backup.quadro_fase_b_operacoes_20261001 AS TABLE public.quadro_operacoes;
CREATE TABLE primeline_backup.quadro_fase_b_funcoes_20261001 AS SELECT p.oid::regprocedure::text assinatura,pg_get_functiondef(p.oid) definicao,p.proacl::text acl,pg_get_userbyid(p.proowner) owner FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.prokind='f' AND (p.proname LIKE 'fn_quadro_%' OR p.proname='fn_registar_movimento_quadro');
CREATE TABLE primeline_backup.quadro_fase_b_policies_20261001 AS SELECT * FROM pg_policies WHERE schemaname='public' AND tablename IN('quadro_pessoal_alocacao','quadro_pessoal_movimentos');
CREATE TABLE primeline_backup.quadro_fase_b_acl_tabelas_20261001 AS SELECT * FROM primeline_backup.quadro_acl_tabelas_20261001 WITH NO DATA;
INSERT INTO primeline_backup.quadro_fase_b_acl_tabelas_20261001 SELECT c.oid::regclass::text,e.* FROM pg_class c CROSS JOIN LATERAL aclexplode(coalesce(c.relacl,acldefault('r',c.relowner))) e WHERE c.oid IN('public.quadro_pessoal_alocacao'::regclass,'public.quadro_pessoal_movimentos'::regclass);
CREATE TABLE primeline_backup.quadro_fase_b_acl_funcoes_20261001 AS SELECT * FROM primeline_backup.quadro_acl_funcoes_20261001 WITH NO DATA;
INSERT INTO primeline_backup.quadro_fase_b_acl_funcoes_20261001 SELECT p.oid::regprocedure::text,e.* FROM pg_proc p JOIN primeline_backup.quadro_fase_b_funcoes_20261001 b ON p.oid::regprocedure::text=b.assinatura CROSS JOIN LATERAL aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) e;
CREATE TABLE primeline_backup.quadro_fase_b_colunas_20261001 AS SELECT a.attrelid::regclass::text tabela,a.attname,a.attnotnull,a.attacl,a.atttypid,pg_get_expr(d.adbin,d.adrelid) valor_default FROM pg_attribute a LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum WHERE a.attrelid IN('public.quadro_pessoal_alocacao'::regclass,'public.quadro_pessoal_movimentos'::regclass) AND a.attnum>0 AND NOT a.attisdropped;
CREATE TABLE primeline_backup.quadro_fase_b_acl_colunas_20261001 AS SELECT a.attrelid::regclass::text tabela,a.attname,e.* FROM pg_attribute a CROSS JOIN LATERAL aclexplode(a.attacl) e WHERE a.attrelid IN('public.quadro_pessoal_alocacao'::regclass,'public.quadro_pessoal_movimentos'::regclass) AND a.attnum>0 AND NOT a.attisdropped;
CREATE TABLE primeline_backup.quadro_fase_b_tabelas_20261001 AS SELECT oid::regclass::text tabela,pg_get_userbyid(relowner) owner,relacl,relrowsecurity,relforcerowsecurity FROM pg_class WHERE oid IN('public.quadro_pessoal_alocacao'::regclass,'public.quadro_pessoal_movimentos'::regclass);
CREATE TABLE primeline_backup.quadro_fase_b_triggers_20261001 AS SELECT tgrelid::regclass::text tabela,tgname,tgenabled,pg_get_triggerdef(oid) definicao FROM pg_trigger WHERE tgrelid IN('public.quadro_pessoal_alocacao'::regclass,'public.quadro_pessoal_movimentos'::regclass) AND NOT tgisinternal;
-- Structural reference is captured ONLY from the validated A catalog, before B.
-- Never refresh this reference from an already installed B or from a postcheck.
CREATE TABLE primeline_backup.quadro_fase_b_estrutura_20261001 AS
SELECT jsonb_build_object(
 'functions',coalesce((SELECT jsonb_agg(jsonb_build_object('signature',format('%I.%I(%s)',n.nspname,p.proname,oidvectortypes(p.proargtypes)),
   'definition',md5(replace(pg_get_functiondef(p.oid),chr(13),'')),'owner',pg_get_userbyid(p.proowner),'sd',p.prosecdef,'config',p.proconfig,
   'acl',(SELECT jsonb_agg(jsonb_build_object('grantee',CASE WHEN x.grantee=0 THEN 'PUBLIC' ELSE pg_get_userbyid(x.grantee)::text END,'grantor',pg_get_userbyid(x.grantor),'privilege',x.privilege_type,'grantable',x.is_grantable) ORDER BY CASE WHEN x.grantee=0 THEN 'PUBLIC' ELSE pg_get_userbyid(x.grantee)::text END,x.privilege_type) FROM aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) x)) ORDER BY n.nspname,p.proname,oidvectortypes(p.proargtypes))
  FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE p.prokind IN('f','p') AND
  ((n.nspname='public' AND (p.proname LIKE 'fn_quadro_%' OR p.proname LIKE 'fn_rh_%' OR p.proname IN('fn_criar_colaborador_com_alocacao','fn_registar_movimento_quadro','fn_pode_gerir_quadro','fn_pode_consultar_quadro','fn_listar_ponto_obra','fn_guardar_ponto_obra') OR p.prosrc ILIKE '%quadro_pessoal_alocacao%' OR p.prosrc ~* '(^|[^a-z_])execute([^a-z_]|$)' OR 'regclass'::regtype=ANY(p.proargtypes::oid[]) OR p.oid IN(SELECT tgfoid FROM pg_trigger WHERE tgrelid IN('public.quadro_pessoal_alocacao'::regclass,'public.quadro_pessoal_movimentos'::regclass) AND NOT tgisinternal))) OR n.nspname='primeline_quadro_rollout')),'[]'::jsonb),
 'tables',coalesce((SELECT jsonb_agg(jsonb_build_object('table',format('%I.%I',n.nspname,c.relname),'owner',pg_get_userbyid(c.relowner),'rls',c.relrowsecurity,'force_rls',c.relforcerowsecurity,
   'acl',(SELECT jsonb_agg(jsonb_build_object('grantee',CASE WHEN x.grantee=0 THEN 'PUBLIC' ELSE pg_get_userbyid(x.grantee)::text END,'grantor',pg_get_userbyid(x.grantor),'privilege',x.privilege_type,'grantable',x.is_grantable) ORDER BY CASE WHEN x.grantee=0 THEN 'PUBLIC' ELSE pg_get_userbyid(x.grantee)::text END,x.privilege_type) FROM aclexplode(coalesce(c.relacl,acldefault('r',c.relowner))) x)) ORDER BY n.nspname,c.relname)
  FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE c.oid=ANY(ARRAY['public.quadro_pessoal_alocacao'::regclass,'public.quadro_pessoal_movimentos'::regclass,'public.quadro_pessoal_rpc_permit'::regclass,'public.quadro_dias_revisoes'::regclass,'public.quadro_operacoes'::regclass,'public.quadro_escrita_interna'::regclass,'primeline_quadro_rollout.controlo'::regclass,'primeline_quadro_rollout.validacoes'::regclass])),'[]'::jsonb),
 'columns',coalesce((SELECT jsonb_agg(jsonb_build_object('table',format('%I.%I',n.nspname,c.relname),'name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'notnull',a.attnotnull,'default',pg_get_expr(d.adbin,d.adrelid),
   'acl',(SELECT jsonb_agg(jsonb_build_object('grantee',CASE WHEN x.grantee=0 THEN 'PUBLIC' ELSE pg_get_userbyid(x.grantee)::text END,'grantor',pg_get_userbyid(x.grantor),'privilege',x.privilege_type,'grantable',x.is_grantable) ORDER BY CASE WHEN x.grantee=0 THEN 'PUBLIC' ELSE pg_get_userbyid(x.grantee)::text END,x.privilege_type) FROM aclexplode(a.attacl) x)) ORDER BY n.nspname,c.relname,a.attnum)
  FROM pg_attribute a JOIN pg_class c ON c.oid=a.attrelid JOIN pg_namespace n ON n.oid=c.relnamespace LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
  WHERE a.attrelid=ANY(ARRAY['public.quadro_pessoal_alocacao'::regclass,'public.quadro_pessoal_movimentos'::regclass,'public.quadro_pessoal_rpc_permit'::regclass,'public.quadro_dias_revisoes'::regclass,'public.quadro_operacoes'::regclass,'public.quadro_escrita_interna'::regclass,'primeline_quadro_rollout.controlo'::regclass,'primeline_quadro_rollout.validacoes'::regclass]) AND a.attnum>0 AND NOT a.attisdropped),'[]'::jsonb),
 'triggers',coalesce((SELECT jsonb_agg(jsonb_build_object('table',format('%I.%I',n.nspname,c.relname),'name',t.tgname,'enabled',t.tgenabled,'type',t.tgtype,'function',t.tgfoid::regprocedure::text,'definition',pg_get_triggerdef(t.oid)) ORDER BY n.nspname,c.relname,t.tgname)
  FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE t.tgrelid IN('public.quadro_pessoal_alocacao'::regclass,'public.quadro_pessoal_movimentos'::regclass) AND NOT t.tgisinternal),'[]'::jsonb),
 'constraints',coalesce((SELECT jsonb_agg(jsonb_build_object('table',format('%I.%I',n.nspname,c.relname),'name',x.conname,'definition',pg_get_constraintdef(x.oid),'validated',x.convalidated) ORDER BY n.nspname,c.relname,x.conname)
  FROM pg_constraint x JOIN pg_class c ON c.oid=x.conrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE x.conrelid=ANY(ARRAY['public.quadro_pessoal_alocacao'::regclass,'public.quadro_pessoal_movimentos'::regclass,'public.quadro_pessoal_rpc_permit'::regclass,'public.quadro_dias_revisoes'::regclass,'public.quadro_operacoes'::regclass,'public.quadro_escrita_interna'::regclass,'primeline_quadro_rollout.controlo'::regclass,'primeline_quadro_rollout.validacoes'::regclass])),'[]'::jsonb),
 'indexes',coalesce((SELECT jsonb_agg(jsonb_build_object('name',format('%I.%I',n.nspname,c.relname),'definition',pg_get_indexdef(i.indexrelid),'valid',i.indisvalid,'ready',i.indisready) ORDER BY n.nspname,c.relname)
  FROM pg_index i JOIN pg_class c ON c.oid=i.indexrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE i.indrelid=ANY(ARRAY['public.quadro_pessoal_alocacao'::regclass,'public.quadro_pessoal_movimentos'::regclass,'public.quadro_pessoal_rpc_permit'::regclass,'public.quadro_dias_revisoes'::regclass,'public.quadro_operacoes'::regclass,'public.quadro_escrita_interna'::regclass,'primeline_quadro_rollout.controlo'::regclass,'primeline_quadro_rollout.validacoes'::regclass]) OR c.relname='alertas_ocorrencia_unica_idx'),'[]'::jsonb),
 'policies',coalesce((SELECT jsonb_agg(jsonb_build_object('schema',p.schemaname,'table',p.tablename,'name',p.policyname,'permissive',p.permissive,'cmd',p.cmd,'roles',p.roles,'qual',md5(p.qual),'check',md5(p.with_check)) ORDER BY p.schemaname,p.tablename,p.policyname)
  FROM pg_policies p WHERE (p.schemaname='public' AND p.tablename IN('quadro_pessoal_alocacao','quadro_pessoal_movimentos','quadro_pessoal_rpc_permit','quadro_dias_revisoes','quadro_operacoes','quadro_escrita_interna')) OR p.schemaname='primeline_quadro_rollout'),'[]'::jsonb),
 'schema', (SELECT jsonb_build_object('name',n.nspname,'owner',pg_get_userbyid(n.nspowner),'acl',(SELECT jsonb_agg(jsonb_build_object('grantee',CASE WHEN x.grantee=0 THEN 'PUBLIC' ELSE pg_get_userbyid(x.grantee)::text END,'grantor',pg_get_userbyid(x.grantor),'privilege',x.privilege_type,'grantable',x.is_grantable) ORDER BY CASE WHEN x.grantee=0 THEN 'PUBLIC' ELSE pg_get_userbyid(x.grantee)::text END,x.privilege_type) FROM aclexplode(coalesce(n.nspacl,acldefault('n',n.nspowner))) x)) FROM pg_namespace n WHERE n.nspname='primeline_quadro_rollout')
) AS estrutura;
REVOKE ALL ON ALL TABLES IN SCHEMA primeline_backup FROM PUBLIC,anon,authenticated,service_role;
COMMIT;
