import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
const app = await readFile(new URL("../src/app.js", import.meta.url), "utf8");
const migration = await readFile(new URL("../supabase/quadro_pessoal_20260925/00_regras_movimentacoes.sql", import.meta.url), "utf8");
assert(!app.includes("allowsMultipleWorks"));
assert(!app.includes("isWorkforceForeman"));
assert(app.includes("data-source-ids="));
assert(app.includes("selectedWorkforceSourceIds.length !== 1"));
assert(app.includes('workforceRequest(supabase, "remover", payload'));
const validator = migration.slice(migration.indexOf('FUNCTION public.fn_validar_conflito_quadro_pessoal'), migration.indexOf('ALTER TABLE public.quadro_pessoal_alocacao DROP'));
assert(!validator.includes('permite_multiplas_obras'));
assert(!validator.includes('funcao'));
assert(migration.includes('NULLS NOT DISTINCT'));
assert(migration.includes('Alocação idêntica já existente.'));
console.log("Múltiplas obras universais e remoção por ID validadas.");
