import test from 'node:test';import assert from 'node:assert/strict';
import {allocationsForDate,createWorkforceAllocationClient} from '../src/workforce-allocation.js';
const values={colaborador_id:'person',data:'2026-10-05',periodo:'manha',obra_id:'work',tipo_alocacao:'obra',expected_revision:2};
const preview={version:1,committed:false,versao:'snapshot'};
const confirmed={version:1,committed:true,idempotent:false,revision:3,allocations:[{id:'allocation',data:values.data}]};
function mock(responses){const calls=[];let reloads=0;const client=createWorkforceAllocationClient({requestId:()=> 'request-uuid',reload:async()=>{reloads++;},supabase:async(path,options)=>{calls.push({path,body:JSON.parse(options.body)});const next=responses.shift();if(next instanceof Error)throw next;return Response.json(next.body??next,{status:next.status??200});}});return {calls,client,reloads:()=>reloads};}
test('resolver usa data exata, sem herança nem responsabilidade',()=>{const yesterday={id:'a',data:'2026-10-04'},today={id:'b',data:'2026-10-05'};assert.deepEqual(allocationsForDate([yesterday,today],values.data),[today]);assert.deepEqual(allocationsForDate([yesterday],values.data),[]);});
test('preview e uma confirmação: contrato, revisão, request e snapshot estáveis',async()=>{const m=mock([preview,confirmed]);assert.deepEqual(await m.client.execute('alocar',values),confirmed);assert.equal(m.calls.length,2);assert.ok(m.calls.every(c=>c.path==='rpc/fn_quadro_operar'));assert.deepEqual(m.calls[0].body.p_dados,{...values,version:1,request_id:'request-uuid'});assert.deepEqual(m.calls[1].body.p_dados,m.calls[0].body.p_dados);assert.equal(m.calls[1].body.p_versao,'snapshot');assert.equal(m.calls[0].body.p_confirmar,false);assert.equal(m.calls[1].body.p_confirmar,true);});
test('resposta sem committed=true não confirma sucesso',async()=>{const m=mock([preview,{...confirmed,committed:false}]);await assert.rejects(m.client.execute('alocar',values),/não confirmou/);assert.equal(m.calls.length,2);});
test('preview inválido não envia confirmação',async()=>{const m=mock([{version:1,committed:false}]);await assert.rejects(m.client.execute('alocar',values),/preview/);assert.equal(m.calls.length,1);});
test('STALE_REVISION recarrega e não repete com revisão nova',async()=>{const m=mock([preview,{body:{message:'STALE_REVISION'},status:400}]);await assert.rejects(m.client.execute('alocar',values),/alterada por outro utilizador/);assert.equal(m.reloads(),1);assert.equal(m.calls.length,2);});
for(const [message,expect] of [['PERMISSION_DENIED',/permissão/],['ABSENCE_CONFLICT',/ausência/],['LEGACY_CONFLICT',/sobrepostas/],['IDEMPOTENCY_CONFLICT',/outra operação/]])test(message+' mantém o pedido sem retry',async()=>{const m=mock([{body:{message},status:400}]);await assert.rejects(m.client.execute('alocar',values),expect);assert.equal(m.calls.length,1);assert.equal(m.reloads(),0);});
test('erro de rede na confirmação não repete RPC nem assume gravação',async()=>{const m=mock([preview,new Error('Network unavailable')]);await assert.rejects(m.client.execute('alocar',values),/Network/);assert.equal(m.calls.length,2);});
test('replay confirmado aceite sem segunda confirmação',async()=>{const m=mock([preview,{...confirmed,idempotent:true}]);assert.equal((await m.client.execute('remover',{...values,ids:['allocation']})).idempotent,true);assert.equal(m.calls.length,2);});
