import { platformConfirm } from "./platform-dialogs.js?v=2";

const esc = value => String(value ?? "").replace(/[&<>"']/g, character => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#039;" })[character]);
const today = () => new Date().toISOString().slice(0, 10);
const monthKey = value => String(value || today()).slice(0, 7);
const time = value => String(value || "").slice(0, 5);
const shortName = value => { const parts=String(value||"").trim().split(/\s+/).filter(Boolean); return parts.length>1?`${parts[0]} ${parts.at(-1)}`:(parts[0]||"Utilizador"); };
const dateLabel = value => new Intl.DateTimeFormat("pt-PT",{weekday:"short",day:"2-digit",month:"short"}).format(new Date(`${value}T12:00:00`));
const monthLabel = value => new Intl.DateTimeFormat("pt-PT",{month:"long",year:"numeric"}).format(new Date(`${value}-01T12:00:00`));
function moveMonth(value, offset){const date=new Date(`${value}-01T12:00:00`);date.setMonth(date.getMonth()+offset);return date.toISOString().slice(0,7);}
function days(value){const [year,month]=value.split("-").map(Number),first=new Date(year,month-1,1,12);return [...Array.from({length:(first.getDay()+6)%7},()=>null),...Array.from({length:new Date(year,month,0,12).getDate()},(_,i)=>`${year}-${String(month).padStart(2,"0")}-${String(i+1).padStart(2,"0")}`)];}
const CATEGORY={reuniao:"REUNIÃO",visita_obra:"VISITA À OBRA",prazo:"PRAZO",fornecedor:"FORNECEDOR",cliente:"CLIENTE",outro:"OUTRO"};

export function createCalendarModule({root,supabase,isConfigured,getProfile,toast}){
  const state={loaded:false,loading:false,events:[],participants:[],users:[],works:[],month:monthKey(),selectedDate:today(),editingId:"",error:""};
  async function api(path,options={}){const response=await supabase(path,options);if(!response.ok){const payload=await response.json().catch(()=>({}));throw new Error(payload.message||payload.details||"Não foi possível consultar a Agenda.");}return response.status===204?[]:response.json();}
  const participantIds=id=>state.participants.filter(row=>row.compromisso_id===id).map(row=>row.utilizador_id);
  const eventsFor=date=>state.events.filter(row=>row.data===date).sort((a,b)=>String(a.hora_inicio||"").localeCompare(String(b.hora_inicio||"")));
  const workLabel=id=>{const row=state.works.find(item=>item.id===id);return row?`${row.numero||"—"} · ${row.nome}`:"";};
  const canManage=row=>row?.criado_por===getProfile()?.id||row?.responsavel_id===getProfile()?.id||["gestao_plataforma","gerencia"].includes(String(getProfile()?.funcao||""));
  async function load(force=false){if(state.loading||(state.loaded&&!force))return render();state.loading=true;state.error="";render();try{if(!isConfigured){state.events=[];state.participants=[];state.users=[{id:"colega-demo",nome:"Colega Demo",funcao:"adjunto"}];state.works=[];}else [state.events,state.participants,state.users,state.works]=await Promise.all([
    api("compromissos?select=*&order=data.asc,hora_inicio.asc.nullslast"),api("compromissos_participantes?select=compromisso_id,utilizador_id"),api("rpc/fn_listar_colegas_agenda",{method:"POST",body:"{}"}),api("obras?select=id,numero,nome&situacao=in.(preparacao,em_curso)&order=numero")]);state.loaded=true;}catch(error){state.error=error.message;}finally{state.loading=false;render();}}
  function eventCard(row){const people=participantIds(row.id).map(id=>state.users.find(user=>user.id===id)).filter(Boolean);return `<article class="calendar-event category-${esc(row.categoria)}"><time>${row.dia_inteiro?"DIA INTEIRO":`${time(row.hora_inicio)}–${time(row.hora_fim)}`}</time><div><span>${esc(CATEGORY[row.categoria]||row.categoria)}</span><strong>${esc(row.titulo)}</strong><small>${esc(workLabel(row.obra_id)||row.local||"Sem local associado")}</small>${people.length?`<em>COM ${people.map(person=>esc(shortName(person.nome))).join(", ")}</em>`:""}</div>${canManage(row)?`<div><button type="button" data-edit-calendar="${row.id}">EDITAR</button><button type="button" class="danger" data-delete-calendar="${row.id}">APAGAR</button></div>`:""}</article>`;}
  function calendar(){return `<section class="agenda-calendar panel"><header><button type="button" data-calendar-month="-1">←</button><div><p class="eyebrow">CALENDÁRIO</p><h2>${esc(monthLabel(state.month))}</h2></div><button type="button" data-calendar-month="1">→</button></header><div class="agenda-weekdays">${["SEG","TER","QUA","QUI","SEX","SÁB","DOM"].map(day=>`<span>${day}</span>`).join("")}</div><div class="agenda-month-grid">${days(state.month).map(date=>!date?'<span class="agenda-day empty"></span>':`<button type="button" class="agenda-day ${date===state.selectedDate?"selected":""} ${date===today()?"today":""}" data-calendar-date="${date}"><b>${Number(date.slice(-2))}</b><span>${eventsFor(date).slice(0,3).map(row=>`<i class="category-${esc(row.categoria)}">${row.dia_inteiro?"•":time(row.hora_inicio)} ${esc(row.titulo)}</i>`).join("")}</span>${eventsFor(date).length>3?`<em>+${eventsFor(date).length-3}</em>`:""}</button>`).join("")}</div></section>`;}
  function form(){const row=state.events.find(item=>item.id===state.editingId),checked=new Set(row?participantIds(row.id):[]),colleagues=state.users.filter(user=>user.id!==getProfile()?.id);return `<section class="agenda-form panel"><header><p class="eyebrow">${row?"ALTERAR":"NOVO"}</p><h2>${row?"EDITAR COMPROMISSO":"REGISTAR COMPROMISSO"}</h2></header><form data-calendar-form><label>TÍTULO<input name="titulo" required maxlength="180" value="${esc(row?.titulo||"")}"></label><div class="agenda-form-grid"><label>DATA<input name="data" type="date" required value="${row?.data||state.selectedDate}"></label><label>CATEGORIA<select name="categoria">${Object.entries(CATEGORY).map(([value,label])=>`<option value="${value}" ${row?.categoria===value?"selected":""}>${label}</option>`).join("")}</select></label><label>INÍCIO<input name="hora_inicio" type="time" value="${time(row?.hora_inicio)}"></label><label>FIM<input name="hora_fim" type="time" value="${time(row?.hora_fim)}"></label></div><label class="agenda-all-day"><input name="dia_inteiro" type="checkbox" ${row?.dia_inteiro?"checked":""}> DIA INTEIRO</label><div class="agenda-form-grid"><label>OBRA (OPCIONAL)<select name="obra_id"><option value="">Sem obra</option>${state.works.map(work=>`<option value="${work.id}" ${row?.obra_id===work.id?"selected":""}>${esc(workLabel(work.id))}</option>`).join("")}</select></label><label>LOCAL / LIGAÇÃO<input name="local" maxlength="240" value="${esc(row?.local||"")}"></label><label>PRIORIDADE<select name="prioridade">${["normal","alta"].map(value=>`<option value="${value}" ${row?.prioridade===value?"selected":""}>${value.toUpperCase()}</option>`).join("")}</select></label><label>LEMBRETE<select name="lembrete_dias">${[[0,"NO PRÓPRIO DIA"],[1,"1 DIA ANTES"],[7,"7 DIAS ANTES"]].map(([value,label])=>`<option value="${value}" ${Number(row?.lembrete_dias??1)===value?"selected":""}>${label}</option>`).join("")}</select></label></div><label>NOTAS<textarea name="descricao" rows="3" maxlength="1500">${esc(row?.descricao||"")}</textarea></label><fieldset class="agenda-participants"><legend>MARCAR COLEGAS</legend><p>Os colegas selecionados verão o compromisso e receberão um alerta.</p><div>${colleagues.length?colleagues.map(user=>`<label><input type="checkbox" name="participantes" value="${user.id}" ${checked.has(user.id)?"checked":""}><span>${esc(shortName(user.nome))}</span><small>${esc(String(user.funcao||"Utilizador").replaceAll("_"," "))}</small></label>`).join(""):'<small class="agenda-no-colleagues">Não existem outros colegas ativos.</small>'}</div></fieldset><div class="agenda-form-actions"><button type="submit" class="primary-button">${row?"GUARDAR ALTERAÇÕES":"REGISTAR"} →</button>${row?'<button type="button" class="outline-action" data-cancel-calendar>CANCELAR</button>':""}</div><p class="form-error"></p></form></section>`;}
  function render(){const selected=eventsFor(state.selectedDate);root.innerHTML=`<div class="page-heading"><div><p class="eyebrow">ORGANIZAÇÃO</p><h1>AGENDA</h1><p>Compromissos pessoais e partilhados com colegas.</p></div><div class="heading-stat"><span>PRÓXIMOS</span><strong>${state.events.filter(row=>row.data>=today()).length}</strong></div></div>${state.error?`<div class="work-warning"><strong>AGENDA INDISPONÍVEL</strong><span>${esc(state.error)}</span></div>`:""}${state.loading?'<div class="fleet-loading">A CARREGAR AGENDA…</div>':`<div class="agenda-layout"><div>${calendar()}<section class="agenda-day-list panel"><header><div><p class="eyebrow">COMPROMISSOS</p><h2>${esc(dateLabel(state.selectedDate))}</h2></div><span>${selected.length}</span></header>${selected.length?selected.map(eventCard).join(""):'<p class="meeting-empty">Sem compromissos neste dia.</p>'}</section></div>${form()}</div>`}`;}
  root.addEventListener("click",async event=>{const month=event.target.closest("[data-calendar-month]");if(month){state.month=moveMonth(state.month,Number(month.dataset.calendarMonth));render();return;}const day=event.target.closest("[data-calendar-date]");if(day){state.selectedDate=day.dataset.calendarDate;state.editingId="";render();return;}const edit=event.target.closest("[data-edit-calendar]");if(edit){const row=state.events.find(item=>item.id===edit.dataset.editCalendar);if(!canManage(row))return toast("Não tem permissão para editar este compromisso.","error");state.editingId=row.id;state.selectedDate=row.data;state.month=monthKey(row.data);render();return;}if(event.target.closest("[data-cancel-calendar]")){state.editingId="";render();return;}const remove=event.target.closest("[data-delete-calendar]");if(remove){const row=state.events.find(item=>item.id===remove.dataset.deleteCalendar);if(!row||!canManage(row))return;if(!await platformConfirm(`Apagar o compromisso “${row.titulo}”?`,{title:"Apagar compromisso",danger:true,confirmLabel:"APAGAR"}))return;remove.disabled=true;try{if(isConfigured)await api("rpc/fn_apagar_compromisso",{method:"POST",body:JSON.stringify({p_compromisso_id:row.id})});state.events=state.events.filter(item=>item.id!==row.id);state.participants=state.participants.filter(item=>item.compromisso_id!==row.id);state.editingId="";toast("Compromisso apagado.");render();}catch(error){toast(error.message,"error");remove.disabled=false;}}});
  root.addEventListener("submit",async event=>{const element=event.target.closest("[data-calendar-form]");if(!element)return;event.preventDefault();const button=element.querySelector('button[type="submit"]'),errorNode=element.querySelector(".form-error"),data=new FormData(element),fields=Object.fromEntries(data),participants=data.getAll("participantes"),allDay=fields.dia_inteiro==="on";errorNode.textContent="";if(!allDay&&(!fields.hora_inicio||!fields.hora_fim||fields.hora_fim<=fields.hora_inicio))return void(errorNode.textContent="Indique um horário válido ou selecione Dia inteiro.");button.disabled=true;try{const payload={p_compromisso_id:state.editingId||null,p_titulo:fields.titulo.trim(),p_data:fields.data,p_hora_inicio:allDay?null:fields.hora_inicio,p_hora_fim:allDay?null:fields.hora_fim,p_dia_inteiro:allDay,p_categoria:fields.categoria,p_obra_id:fields.obra_id||null,p_responsavel_id:getProfile()?.id||null,p_local:fields.local.trim()||null,p_descricao:fields.descricao.trim()||null,p_prioridade:fields.prioridade,p_lembrete_dias:Number(fields.lembrete_dias),p_participantes:participants};let saved={id:state.editingId||crypto.randomUUID(),criado_por:getProfile()?.id,...payload,data:payload.p_data,hora_inicio:payload.p_hora_inicio,hora_fim:payload.p_hora_fim,dia_inteiro:allDay,categoria:payload.p_categoria,obra_id:payload.p_obra_id,responsavel_id:payload.p_responsavel_id,local:payload.p_local,descricao:payload.p_descricao,prioridade:payload.p_prioridade,lembrete_dias:payload.p_lembrete_dias,titulo:payload.p_titulo};if(isConfigured){const result=await api("rpc/fn_guardar_compromisso",{method:"POST",body:JSON.stringify(payload)});saved=Array.isArray(result)?result[0]:result;}state.events=state.events.filter(item=>item.id!==saved.id).concat(saved);state.participants=state.participants.filter(item=>item.compromisso_id!==saved.id).concat(participants.map(utilizador_id=>({compromisso_id:saved.id,utilizador_id})));state.selectedDate=saved.data;state.month=monthKey(saved.data);state.editingId="";toast(participants.length?"Compromisso guardado e colegas notificados.":"Compromisso guardado.");render();}catch(error){errorNode.textContent=error.message;button.disabled=false;}});
  return {show:()=>load(true),refresh:()=>load(true)};
}
